<?php
    
    /********** Hallify's Configuration Script **********
     * 
     * ** Basic Configuration ** *
     * 1 - VERSION - Hallify's version
     * 2 - ENVIRONMENT - Hallify's environment (development/production)
     *
     * ** URL Configuration ** *
     * 1 - URL_PUBLIC_FOLDER - Hallify's public folder
     * 2 - URL_PROTOCOL - Hallify's protocol
     * 3 - URL_DOMAIN - Hallify's domain name (depends on ENVIRONMENT)
     * 4 - URL_SUB_FOLDER - Hallify's sub folder
     * 5 - URL - Hallify's autogenerated URL (depends on ENVIRONMENT)
     *
     * ** Parse Configuration ** *
     * 1 - 
     *
     * ** SQL Database Configuration ** *
     * 1 - 
     *
     * ** Third Party Libraries Configuration ** *
     * 1 -
     *
     */


    /********** Basic Configuration **********/

    /**
     * Hallify's Version
     **/
    define("VERSION", "1.0 (beta)");

    /**
     * Hallify's Environment
     **/
    define("ENVIRONMENT", "development");

    /**
     * Enable error reporting inf the ENVIRONMENT is set to "development"
     **/
    if (ENVIRONMENT === "development" || ENVIRONMENT === "dev") {

    	error_reporting(E_ALL);
    	ini_set("display_errors", 1);
    }


    /********** URL Configuration **********/

    /**
     * Hallify's Public Folder
     **/
    define("URL_PUBLIC_FOLDER", "public");

    /**
     * Hallify's URL Protocol
     **/
    define("URL_PROTOCOL", "http://");

    /**
     * Hallify's Domain
     **/
    define("URL_DOMAIN", $_SERVER["HTTP_HOST"]);

    /**
     * Hallify's Sub Folder
     **/
    define("URL_SUB_FOLDER", str_replace(URL_PUBLIC_FOLDER, '', dirname($_SERVER["SCRIPT_NAME"])));
    
    /**
     * Hallify's Autogenerated URL
     **/
    define("URL", URL_PROTOCOL . URL_DOMAIN . URL_SUB_FOLDER);


    /********** Parse Configuration **********/


    /********** SQL Database Configuration **********/


    /********** Third Party Libraries Configuration **********/